<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=gb2312">
    <title>C＋＋异常处理的实现</title>
</head>
<body>
<h3>异常处理的语法</h3>
<p>try，throw，catch语句就是C++语言提供对处理异常情况的语句。</p>
<h3>throw表达式的语法：</h3>
<p>throw 表达式；</p>
<h3>try块的语法：</h3>
<p>try<br>
    复合语句<br>
    catch（异常声明）<br>
    复合语句<br>
    catch（异常声明）<br>
    复合语句<br>
    …</p>
<h3>异常处理的执行过程：</h3>
<p>（1）程序通过正常的执行顺序到达try语句，然后执行try块内的保护段。<br>
    （2）如果在保护段执行期间没有引起异常，那么跟在try块后的catch子句就不执行。程序从异常被抛掷的try块后跟随的最后一个catch子句后面的语句继续执行下去。<br>
    （3）程序执行到一个throw表达式时，一个异常对象会被创建。若异常的抛出点本身在一个try子句内，则该try语句后的catch子句会按顺序检查异常类型是否与声明的类型匹配；若异常抛出点本身不在任何try子句内，或抛出的异常与各个catch子句所声明的类型都不匹配，则结束当前函数的执行，回到当前函数的调用点，把调用点作为异常的抛出点，然后重复这一过程。此处理继续下去，直到异常成功被一个catch语句捕获。<br>
    （4）如果始终没有找到与被抛掷异常匹配的catch子句，最终main函数会结束执行，则运行库函数terminate将被自动调用，其terminate的默认功能是调用abort终止程序。<br>
    （5）如果找到了一个匹配的catch子句，则catch子句后的复合语句会被执行。复合语句执行完毕后，当前的try块（包括try子句和一系列catch子句）即执行完毕。</p>

<h3>异常接口声明</h3>
<p>为了加强程序的可读性，使函数的用户能够方便地知道所使用的函数会抛掷哪些异常，可以在函数的声明中列出这个函数可能抛掷的所有的异常类型。例如：<br>
    void fun() throw(A, B, C, D);<br>
    表明函数fun()能且仅能抛掷类型A, B, C, D及其子类型的异常。<br>
    如果在函数的声明中没有包括异常接口声明，则此函数可以抛掷任何类型的异常。例如：<br>
    void fun();<br>
    一个不抛掷任何类型异常的函数可以进行如下形式的声明：<br>
    void fun() throw();</p>
</body>
</html>